---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 在 14 天免费试用结束后、有两种方式可以支付同步关系的费用。第一种选择是按需购买。第二种选择是直接从 NetApp 购买许可证。 
---
= 免费试用结束后支付同步关系费用
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在 14 天免费试用结束后、有两种方式可以支付同步关系的费用。第一种选择是从 AWS 或 Azure 订阅“按需购买、渐进购买”或“每年支付”。第二种选择是直接从 NetApp 购买许可证。

您可以从 AWS Marketplace 或 Azure Marketplace 订阅。您不能同时从这两个订阅。

您可以选择将 NetApp 的许可证与 Marketplace 订阅结合使用。例如，如果您有 25 个同步关系、则可以使用许可证支付前 20 个同步关系的费用、然后从 AWS 或 Azure 中按原样支付剩余的 5 个同步关系的费用。

link:concept-licensing.html["了解有关许可证工作原理的更多信息。"]。

如果您在免费试用结束后未立即支付费用、您将无法创建任何其他关系。现有关系不会被删除、但您必须订阅或输入许可证才能对其进行任何更改。

许可证应通过BlueXP副本和同步或适用的网站进行管理、而*不是*通过电子钱包进行管理。



== [[AAWS ]]从AWS订阅

AWS 使您可以按需付费或每年支付。

.按需购买的步骤
. 选择*Sync > Licensing*。
. 选择 * AWS *
. 选择*订阅*，然后选择*继续*。
. 从AWS Marketplace订阅、然后重新登录到BlueXP副本和同步服务以完成注册。
+
以下视频显示了该过程：

+
video::video_cloud_sync_registering.mp4[width=848,height=480]


.每年支付的步骤
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["转至 AWS Marketplace 页面。"^]。
. 选择*继续订阅*。
. 选择您的合同选项，然后选择*创建合同*。




== [[azure]]从Azure订阅

Azure 使您可以按需付费或每年支付。

.您需要的内容
在相关订阅中具有“贡献者”或“所有者”权限的 Azure 用户帐户。

.步骤
. 选择*Sync > Licensing*。
. 选择 * Azure * 。
. 选择*订阅*，然后选择*继续*。
. 在Azure门户中、选择*创建*、选择您的选项、然后选择*订阅*。
+
选择 * 按月 * 按小时付费，或者选择 * 按年 * 按前一年付费。

. 部署完成后、在通知弹出窗口中选择SaaS资源的名称。
. 选择*配置帐户*以返回BlueXP副本并同步。
+
以下视频显示了该过程：

+
video::video_cloud_sync_registering_azure.mp4[width=848,height=480]




== [[licenses]]从NetApp购买许可证、然后将其添加到BlueXP  副本并同步

要预先支付同步关系的费用、您必须购买一个或多个许可证、并将其添加到BlueXP副本和同步服务中。

.您需要的内容
您需要提供许可证的序列号以及与许可证关联的 NetApp 支持站点帐户的用户名和密码。

.步骤
. 请发送邮件至： ng-cloudsync-contact@netapp.com ？ Subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purches%20Request[ 联系 NetApp] 购买许可证。
. 在BlueXP中、选择*同步>许可*。
. 选择*添加许可证*并添加所需信息：
+
.. 输入序列号。
.. 选择与要添加的许可证关联的 NetApp 支持站点帐户：
+
*** 如果您的帐户已添加到BlueXP、请从下拉列表中选择它。
*** 如果尚未添加您的帐户，请选择*添加NSS凭证*，输入用户名和密码，选择*注册*，然后从下拉列表中选择。


.. 选择 * 添加 * 。






== 更新许可证

如果您扩展了从NetApp购买的BlueXP副本和同步许可证、则新的到期日期不会在BlueXP副本和同步中自动更新。要刷新到期日期，您需要重新添加许可证。许可证应通过BlueXP副本和同步或适用的网站进行管理、而*不是*通过电子钱包进行管理。

.步骤
. 在BlueXP中、选择*同步>许可*。
. 选择*添加许可证*并添加所需信息：
+
.. 输入序列号。
.. 选择与要添加的许可证关联的 NetApp 支持站点帐户：
.. 选择 * 添加 * 。




.结果
BlueXP复制和同步使用新的到期日期更新现有许可证。
